-- MySQL Script generated by MySQL Workbench
-- Tue Dec 11 22:10:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KnowMoreDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KnowMoreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KnowMoreDB` DEFAULT CHARACTER SET utf8 ;
USE `KnowMoreDB` ;

-- -----------------------------------------------------
-- Table `KnowMoreDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `points` INT ZEROFILL NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`sphere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`sphere` (
  `interest_area_quest_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`interest_area_quest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`question` (
  `quest_id` INT NOT NULL AUTO_INCREMENT,
  `pos_count` INT NULL,
  `neg_count` INT NULL,
  `question` VARCHAR(256) NOT NULL,
  `isModerated` TINYINT(1) NOT NULL,
  `sphere_interest_area_quest_id` INT NOT NULL,
  PRIMARY KEY (`quest_id`),
  INDEX `fk_Question_sphere1_idx` (`sphere_interest_area_quest_id` ASC) ,
  CONSTRAINT `fk_Question_sphere1`
    FOREIGN KEY (`sphere_interest_area_quest_id`)
    REFERENCES `KnowMoreDB`.`sphere` (`interest_area_quest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`answer` (
  `answer_id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(256) NOT NULL,
  `pos_count` INT NULL,
  `neg_countl` INT NULL,
  `isModerated` TINYINT(1) NOT NULL,
  `user_id` INT NOT NULL,
  `quest_id` INT NOT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `fk_Answer_User1_idx` (`user_id` ASC) ,
  INDEX `fk_Answer_Question1_idx` (`quest_id` ASC) ,
  CONSTRAINT `fk_Answer_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `KnowMoreDB`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`quest_id`)
    REFERENCES `KnowMoreDB`.`question` (`quest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`moderation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`moderation` (
  `idModeration` INT NOT NULL,
  `isModerated` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  `answer_id` INT NULL,
  `quest_id` INT NULL,
  PRIMARY KEY (`idModeration`),
  INDEX `fk_Moderation_User1_idx` (`user_id` ASC) ,
  INDEX `fk_Moderation_Answer1_idx` (`answer_id` ASC) ,
  INDEX `fk_Moderation_Question1_idx` (`quest_id` ASC) ,
  CONSTRAINT `fk_Moderation_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `KnowMoreDB`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Moderation_Answer1`
    FOREIGN KEY (`answer_id`)
    REFERENCES `KnowMoreDB`.`answer` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Moderation_Question1`
    FOREIGN KEY (`quest_id`)
    REFERENCES `KnowMoreDB`.`question` (`quest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`user_has_sphere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`user_has_sphere` (
  `user_id` INT NOT NULL,
  `sphere_interest_area_quest_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `sphere_interest_area_quest_id`),
  INDEX `fk_User_has_sphere_sphere1_idx` (`sphere_interest_area_quest_id` ASC) ,
  INDEX `fk_User_has_sphere_User1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_User_has_sphere_User1`
    FOREIGN KEY (`user_id`)
    REFERENCES `KnowMoreDB`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_sphere_sphere1`
    FOREIGN KEY (`sphere_interest_area_quest_id`)
    REFERENCES `KnowMoreDB`.`sphere` (`interest_area_quest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
