-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 17:08:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KnowMoreDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KnowMoreDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KnowMoreDB` DEFAULT CHARACTER SET utf8 ;
USE `KnowMoreDB` ;

-- -----------------------------------------------------
-- Table `KnowMoreDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `points` INT ZEROFILL NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`Moderation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`Moderation` (
  `idModeration` INT NOT NULL,
  `isModerated` TINYINT(1) NULL,
  PRIMARY KEY (`idModeration`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`Interest_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`Interest_area` (
  `area_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `know_level` VARCHAR(45) NOT NULL,
  `User_user_id` INT NOT NULL,
  PRIMARY KEY (`area_id`),
  INDEX `fk_Interest_area_User1_idx` (`User_user_id` ASC),
  CONSTRAINT `fk_Interest_area_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `KnowMoreDB`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`Question` (
  `quest_id` INT NOT NULL AUTO_INCREMENT,
  `pos_count` INT NULL,
  `neg_count` INT NULL,
  `question` VARCHAR(45) NOT NULL,
  `isModerated` TINYINT(1) NOT NULL,
  `User_user_id` INT NOT NULL,
  `Moderation_idModeration` INT NOT NULL,
  `Interest_area_area_id` INT NOT NULL,
  PRIMARY KEY (`quest_id`),
  INDEX `fk_Question_User1_idx` (`User_user_id` ASC),
  INDEX `fk_Question_Moderation1_idx` (`Moderation_idModeration` ASC),
  INDEX `fk_Question_Interest_area1_idx` (`Interest_area_area_id` ASC),
  CONSTRAINT `fk_Question_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `KnowMoreDB`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_Moderation1`
    FOREIGN KEY (`Moderation_idModeration`)
    REFERENCES `KnowMoreDB`.`Moderation` (`idModeration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_Interest_area1`
    FOREIGN KEY (`Interest_area_area_id`)
    REFERENCES `KnowMoreDB`.`Interest_area` (`area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KnowMoreDB`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KnowMoreDB`.`Answer` (
  `answer_id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(45) NOT NULL,
  `pos_count` INT NULL,
  `neg_countl` INT NULL,
  `isModerated` TINYINT(1) NOT NULL,
  `User_user_id` INT NOT NULL,
  `Moderation_idModeration` INT NOT NULL,
  `Question_quest_id` INT NOT NULL,
  PRIMARY KEY (`answer_id`),
  INDEX `fk_Answer_User1_idx` (`User_user_id` ASC),
  INDEX `fk_Answer_Moderation1_idx` (`Moderation_idModeration` ASC),
  INDEX `fk_Answer_Question1_idx` (`Question_quest_id` ASC),
  CONSTRAINT `fk_Answer_User1`
    FOREIGN KEY (`User_user_id`)
    REFERENCES `KnowMoreDB`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_Moderation1`
    FOREIGN KEY (`Moderation_idModeration`)
    REFERENCES `KnowMoreDB`.`Moderation` (`idModeration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`Question_quest_id`)
    REFERENCES `KnowMoreDB`.`Question` (`quest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
