use KnowMoreDB;

#INSERT INTO user VALUES ('1','Zubakhina', 'Tatyana', 'Tanya7492401', '250', '12345','tanya_postcrossing@mail.ru'); 
#INSERT INTO user VALUES ('2','Bainova', 'Ekaterina', 'Katunchik', '155', '123456','katya@mail.ru'); 
#INSERT INTO user VALUES ('3','Mochilova', 'Tatyana', 'Tanushka', '350', '123','tanya@mail.ru'); #INSERT INTO question VALUES('1', '0', '0', 'What is 2 * 2?', '1', '2', '1', '1');
#INSERT INTO sphere VALUES ('1', 'Maths');
#INSERT INTO sphere VALUES ('2', 'Literature');
#INSERT INTO sphere VALUES ('3', 'Programming');
#INSERT INTO sphere VALUES ('4', 'Russian language');
#INSERT INTO sphere VALUES ('5', 'Physics');
#INSERT INTO sphere VALUES ('6', 'Foreign languages');
#INSERT INTO sphere VALUES ('7', 'Сhemistry');
#INSERT INTO sphere VALUES ('8', 'Biology');
#INSERT INTO sphere VALUES ('9', 'Geography');
#INSERT INTO sphere VALUES ('10', 'Other');
#INSERT INTO user_has_sphere VALUES('1', '1');
#INSERT INTO user_has_sphere VALUES('1', '2');
#INSERT INTO user_has_sphere VALUES('2', '3');
#INSERT INTO user_has_sphere VALUES('3', '1');
#INSERT INTO question VALUES ('1', '0', '0', 'What is 2*2?', '1', '1');
#INSERT INTO answer VALUES ('1', '4', '0', '0', '1', '1', '1');
INSERT INTO moderation(idModeration, isModerated, user_id, quest_id) VALUES('1', '1', '1', '1');
INSERT INTO moderation(idModeration, isModerated, user_id, answer_id) VALUES ('2', '1', '3', '1');